(() => {
 const slides=[...document.querySelectorAll('.slide')],dots=[...document.querySelectorAll('[data-slide]')],labels=['Salestrack','Sua necessidade','Duas modalidades','Como funciona','Método ROTA','André Kachan','Vamos conversar'];
 const q=s=>document.querySelector(s);let current=0,interest='',path='',paused=matchMedia('(prefers-reduced-motion: reduce)').matches;
 function go(index,focus=false){current=Math.max(0,Math.min(slides.length-1,index));slides.forEach((s,i)=>{s.hidden=i!==current;s.classList.toggle('active',i===current);if(i===current)s.scrollTop=0;});dots.forEach((b,i)=>{if(i===current)b.setAttribute('aria-current','step');else b.removeAttribute('aria-current');});q('#previous').disabled=current===0;q('#next').disabled=current===slides.length-1;q('#slide-counter').textContent=String(current+1).padStart(2,'0')+' / 07';q('#slide-label').textContent=labels[current];document.body.dataset.current=current;history.replaceState(null,'','#'+(current+1));window.dispatchEvent(new CustomEvent('salestrack-slide',{detail:current}));if(focus){const h=slides[current].querySelector('h1,h2');h.tabIndex=-1;h.focus({preventScroll:true});}}
 function updateContact(){const summary=[interest,path==='aprender'?'Quero aprender':path==='fazer'?'Quero que façam por mim':''].filter(Boolean).join('. ');q('#selected-interest').textContent=summary;q('#selected-interest').hidden=!summary;q('#deck-whatsapp').href='https://wa.me/5511989296817?text='+encodeURIComponent('Olá, André! Vim pelo site da Salestrack e vi a apresentação. '+(summary?summary+'. ':'')+'Gostaria de conversar.');const params=new URLSearchParams();if(path)params.set('modo',path);if(interest)params.set('interesse',interest);q('#deck-form').href='index.html'+(params.size?'?'+params:'')+'#conversa';}
 dots.forEach(b=>b.addEventListener('click',()=>go(+b.dataset.slide,true)));q('#previous').addEventListener('click',()=>go(current-1,true));q('#next').addEventListener('click',()=>go(current+1,true));document.querySelectorAll('[data-next]').forEach(b=>b.addEventListener('click',()=>go(current+1,true)));
 document.querySelectorAll('[data-interest]').forEach(b=>b.addEventListener('click',()=>{interest=b.dataset.interest;updateContact();go(2,true);}));document.querySelectorAll('[data-path]').forEach(b=>b.addEventListener('click',()=>{path=b.dataset.path;updateContact();go(3,true);}));
 document.addEventListener('keydown',e=>{if(document.querySelector('dialog[open]')||/INPUT|TEXTAREA|SELECT/.test(e.target.tagName)||e.altKey||e.ctrlKey||e.metaKey)return;if(e.key==='ArrowRight'||e.key==='PageDown'){e.preventDefault();go(current+1,true);}else if(e.key==='ArrowLeft'||e.key==='PageUp'){e.preventDefault();go(current-1,true);}else if(e.key==='Home'){e.preventDefault();go(0,true);}else if(e.key==='End'){e.preventDefault();go(slides.length-1,true);}});
 let touchX=0,touchY=0;document.querySelector('.slides').addEventListener('touchstart',e=>{touchX=e.changedTouches[0].clientX;touchY=e.changedTouches[0].clientY;},{passive:true});document.querySelector('.slides').addEventListener('touchend',e=>{const dx=e.changedTouches[0].clientX-touchX,dy=e.changedTouches[0].clientY-touchY;if(Math.abs(dx)>80&&Math.abs(dx)>Math.abs(dy)*1.7)go(current+(dx<0?1:-1));},{passive:true});
 const motion=q('.motion-toggle');function applyMotion(){document.body.classList.toggle('paused',paused);motion.textContent=paused?'Ativar movimento':'Pausar movimento';motion.setAttribute('aria-pressed',String(paused));window.dispatchEvent(new CustomEvent('salestrack-motion',{detail:{paused}}));}applyMotion();motion.addEventListener('click',()=>{paused=!paused;applyMotion();});matchMedia('(prefers-reduced-motion: reduce)').addEventListener('change',e=>{paused=e.matches;applyMotion();});
 const fs=q('#fullscreen');if(!document.fullscreenEnabled)fs.hidden=true;fs.addEventListener('click',async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{q('#deck-status').textContent='Tela cheia não está disponível neste navegador.';}});document.addEventListener('fullscreenchange',()=>fs.setAttribute('aria-label',document.fullscreenElement?'Sair da tela cheia':'Abrir em tela cheia'));
 const initial=parseInt(location.hash.slice(1),10);go(Number.isFinite(initial)?initial-1:0);updateContact();
})();
